---
title: "R Notebook"
output: html_notebook
---


```{r}
lm_umsatzdaten <- lm(Umsatz ~ Temperatur + factor(Bewoelkung) + holiday + KielerWoche + Windgeschwindigkeit + Wettercode + weekday + month + dayOfMonth + EndOfMonth + BeginningOfMonth + vorfeiertage, umsatzdaten)

lm_umsatzdaten <- lm(Umsatz ~ as.factor(weekday)+Temperatur+KielerWoche+EndOfMonth+BeginningOfMonth, umsatzdaten)
summary(lm_umsatzdaten)
```

```{r}
lm_umsatzdaten2 <- lm(Umsatz~
             as.factor(Warengruppe)+
             Umsatz_Vortag+
             Temperatur+
             weekday+
             as.logical(KielerWoche)+
             month+
             Umsatz_Vormonat+
             #as.factor(Bewoelkung)+
             #Windgeschwindigkeit+
             #as.factor(Wettercode)+
             holiday+
             EndOfMonth
             #BeginningOfMonth+
             #vorfeiertage
             , 
           umsatzdaten)
summary(lm_umsatzdaten2)
```

```{r}
lm_umsatzdaten1 <- lm(Umsatz~
             as.factor(Warengruppe)*
             Umsatz_Vortag*
             Temperatur*
             weekday*
             as.logical(KielerWoche)*
             month*
             Umsatz_Vormonat*
             #as.factor(Bewoelkung)+
             #Windgeschwindigkeit+
             #as.factor(Wettercode)+
             holiday*
             EndOfMonth
             #BeginningOfMonth+
             #vorfeiertage
             , 
           umsatzdaten)
summary(lm_umsatzdaten1)
```


