---
title: "R Notebook"
output: html_notebook
---

nötiges Package laden
```{r}
library(ggplot2)
```

Vergleich von Feiertag und nicht-Feiertag. Gesamt und nach Warengruppe
```{r}
data_holiday <- umsatzdaten %>%
  group_by(Warengruppe, holiday) %>%
  summarise( 
    n=n(),
    mean=mean(Umsatz),
    sd=sd(Umsatz)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))

ggplot(data_holiday)+
  aes(x=holiday, y=mean)+
  geom_bar(stat = "identity")+
  geom_errorbar(aes(x=holiday, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="orange", alpha=0.9, size=1)+
  facet_wrap(~Warengruppe)

ggplot(data_holiday)+
  aes(x=holiday, y=mean)+
  geom_bar(stat = "identity")#+
  geom_errorbar(aes(x=holiday, ymin=mean-ic, ymax=mean+ic), width=0.4, colour="orange", alpha=0.9, size=1)


```

Zusammenhang von Temperatur und Umsatz nach Warengruppe getrennt, mit regression line
```{r}
ggplot(umsatzdaten)+
  aes(x=Temperatur, y=Umsatz)+
  geom_point()+
  geom_smooth(method = lm)+
  facet_wrap(~Warengruppe)
```

